### ISSUE TITLE
Should describe how to create a new project in readme

### ISSUE THREAD

**Issue by idflood** [n8han/spde-examples#1]
I think it's somewhat difficult to add a new project. Maybe you could add a little step-by-step guide of how to create a new exemple. I hope there is a simpler way, but here is my procedure:
1. create a new folder for your projects ( spde-examples/MyProject )
2. create a file called "MyProject.spde" in the newly created folder
3. add a simple code in that file, something like

size(640, 360, P3D)
noStroke()
fill(255, 255, 255)

val rSize = 10
def draw() {
  background(0)
  translate(mouseX, mouseY)
  rect(-rSize, -rSize, rSize_2, rSize_2)
}
1. copy a folder like Flocking/lib_managed in your directory ( should look like MyProject/lib_managed )
2. open the file spde-examples/project/build/ExamplesProject.scala
3. copy the first "lazy val exp...", paste and modify it so it looks like:
   lazy val myProject = project("MyProject", "MyProject", new DefaultSpdeProject(_))
4. in terminal, go to the spde-examples directory
5. type "sbt" and then "reload".
6. type "project MyProject"
7. finally just type "run"

**Comment by n8han** [comment]
You're right, this should be documented, and easier. I'm a little torn between encouraging use of the "graft" project, which allows people to postpone installing sbt, and sending people to spde-examples which has cool stuff to look at.

Perhaps... graft is cool but not all that practical. So, yes we need something that is optimal for people that have already installed sbt and used examples. This is actually a general problem for sbt: how to generate new projects. I've been dodging it for a while, but, it would probably only take a day of coding to make something workable. Hm.

**Comment by n8han** [comment]
Okay, I think I've come up with a good interim solution. There's a new starter project, called "Graft" like the other one but this one requires you to have sbt installed already so it doesn't include a jar and leave installer plugin weirdness in your project.

http://technically.us/spde/Download#source-only

I've linked to it from this project's readme too.
